# Generated by Django 5.2.6 on 2025-11-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
