# Generated by Django 5.2.6 on 2025-11-07 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0002_delete_bookings'),
        ('my_admin', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('alter_mob', models.CharField(blank=True, max_length=11, null=True)),
                ('address', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_qty', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('payment_status', models.CharField(default='Pending', max_length=20, null=True)),
                ('order_status', models.CharField(default='Pending', max_length=20, null=True)),
                ('payment_method', models.CharField(default='None', max_length=11, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='my_admin.customer')),
            ],
        ),
    ]
