# Generated by Django 5.2.6 on 2025-11-14 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_initial'),
        ('my_admin', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products_bookings', to='my_admin.product'),
            preserve_default=False,
        ),
    ]
